### ISSUE TITLE
Function domain is hardcoded as `.svc.cluster.local` and this is not correct for all clusters

### ISSUE THREAD

**Issue by Jc2k** [kubeless/nats-trigger#9]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report

**What happened**:

When generating a request to a function it assumes the domain name is `.svc.cluster.local`. See [here](https://github.com/kubeless/nats-trigger/blob/636593a518346710eaf480b70bc81f4370139cc8/pkg/utils/event_sender.go#L56).

**What you expected to happen**:

One of:

* The suffix is just `.svc` - the dns service will automatically expand it to the full form
* nats-trigger automatically works out the correct FQDN 
* there is a config option to set it.

**How to reproduce it (as minimally and precisely as possible)**:

I have a kubeadm cluster where the networking/dnsDomain setting of `ClusterConfigration` was set to a domain, not cluster.local.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Kubeless version (use `kubeless version`): 1.0.6
- Cloud provider or physical cluster: bare metal

**Comment by jdmeyer3** [comment]
I was able to get around this issue by editing the yaml file like so
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kubeless: nats-trigger-controller
  name: nats-trigger-controller
  namespace: kubeless
spec:
  selector:
    matchLabels:
      kubeless: nats-trigger-controller
  template:
    metadata:
      labels:
        kubeless: nats-trigger-controller
    spec:
      containers:  
      - env:
        - name: "NATS_URL"            # domain override here
          value: "nats://nats.<namespace>.<custom domain>:4222"
```
adding the "NATS_URL" env value allowed me override the default cluster domain
